timeout: '3600s'
steps:
  # Backend
  # Install backend packages
  - name: node:12.19.0
    entrypoint: yarn
    args: ['install']
    dir: 'packages/backend'
  # Create backend .env
  - name: node:12.19.0
    entrypoint: yarn
    args: ['run', 'create-env']
    env:
      - 'CLIENT_TOKEN_SECRET=${_CLIENT_TOKEN_SECRET}'
      - 'MONGODB_CONNECTION_URL=${_MONGODB_CONNECTION_URL}'
      - 'SERVICE_URL=${_SERVICE_URL}'
      - 'DEV_PORT=${_DEV_PORT}'
      - 'ALLOWED_ORIGINS=${_ALLOWED_ORIGINS}'
      - 'CAS_VALIDATE_URL=${_CAS_VALIDATE_URL}'
      - 'COLLEGES=${_COLLEGES}'
      - 'MAJORS=${_MAJORS}'
      - 'MINORS=${_MINORS}'
      - 'NODE_ENV=${_NODE_ENV}'
      - 'TOKEN_EXPIRE_TIME=${_TOKEN_EXPIRE_TIME}'
      - 'MAX_REPORTS=${_MAX_REPORTS}'
      - 'AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}'
      - 'AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}'
      - 'BUCKET=${_BUCKET}'
      - 'REGION=${_REGION}'
      - 'REDISHOST=${_REDISHOST}'
      - 'REDISPORT=${_REDISPORT}'
    dir: 'packages/backend'
  # Build the backend
  - name: node:12.19.0
    entrypoint: yarn
    args: ['run', 'build']
    dir: 'packages/backend'
  # Deploy the backend to App Engine Flex
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', "-v", "$_GAE_VERSION"]
    timeout: '1800s'
    dir: 'packages/backend'
  # Frontend
  # Install frontend packages
  - name: node:12.19.0
    entrypoint: yarn
    args: ['install']
    dir: 'packages/frontend'
  # Create frontend .env
  - name: node:12.19.0
    entrypoint: yarn
    args: ['run', 'create-env']
    env:
      - 'REACT_APP_IDP_LOGOUT_URL=${_REACT_APP_IDP_LOGOUT_URL}'
      - 'REACT_APP_SERVICE_URL=${_REACT_APP_SERVICE_URL}'
      - 'REACT_APP_CAS_AUTH_URL=${_REACT_APP_CAS_AUTH_URL}'
      - 'REACT_APP_BACKEND_AUTH_URL=${_REACT_APP_BACKEND_AUTH_URL}'
      - 'REACT_APP_GQL_URL=${_REACT_APP_GQL_URL}'
      - 'REACT_APP_WS_URL=${_REACT_APP_WS_URL}'
      - 'REACT_APP_TOKEN_NAME=${_REACT_APP_TOKEN_NAME}'
    dir: 'packages/frontend'
  # Build the frontend
  - name: node:12.19.0
    entrypoint: yarn
    args: ['run', 'build']
    dir: 'packages/frontend'
  # Deploy the frontend to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', "-v", "$_GAE_VERSION"]
    timeout: '1800s'
    dir: 'packages/frontend'
  # Set the traffic for the production version of the frontend
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "services", "--project", "$PROJECT_ID", "set-traffic", "--splits", "$_GAE_TRAFFIC"]
