runtime: nodejs
env: flex
service: api
handlers:
  - url: /graphql
    http_headers:
      Access-Control-Allow-Origin: https://ricediscuss.uc.r.appspot.com/
      Access-Control-Allow-Credentials: true
